This folder contains implementations of /tan(x)/ and e^x in ARM-Cortex M4. These
were implemented as part of Assignment 2 of Advanced Arm Architectures course.

* Project Structure:

  - *.s files - contains the assembly code.
                Q1_IMT2016012.s contains implementation of e^x and
                Q2_IMT2016012.s contains implementation of /tan(x)/
  - images/ - This folder contains images which compare the values which i got
              with the values computed from Google's calculator. Image files 
	      are named according to the question. Question 1's image is named
	      as Q1_IMT2016012.png etc.
  - datfiles/ - This folder contains .dat files. Each question has a .dat file.
              Each .dat file contains three columns, first column is the input,
	      second column is the calculated value on ARM, third column is the
	      value calculated from Google's calculator.
  - report.pdf - Contains information about the challenges faced, design and some
                 general implementation on how the graphs were plotted.

  - README.org - This file.


* Instructions to run:

  All these files are to be run on keil simulator. They are developed and tested
  on it.
